# Generated by Django 3.2.12 on 2022-03-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220321_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='post',
            field=models.IntegerField(default=1),
        ),
    ]
