# Generated by Django 4.0.2 on 2022-03-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('KZT', 'KZT'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('CNY', 'CNY')], default='KZT', max_length=10),
        ),
    ]
