# Generated by Django 3.2.13 on 2022-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220321_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.CharField(default='KZT', max_length=10),
        ),
    ]
