# Generated by Django 3.2.12 on 2022-03-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.IntegerField(default=1),
        ),
    ]
