# Generated by Django 4.0.2 on 2022-03-06 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_established', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2022)], verbose_name='year')),
                ('main_products', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=300)),
                ('employee_сount', models.PositiveSmallIntegerField(choices=[(0, '< 15 people'), (1, '16 - 100 people'), (2, '101 - 250 people'), (3, '> 250 people')], default=0)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('transaction_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
