# Generated by Django 4.0.2 on 2022-03-06 16:53

import companies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_established',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), companies.models.max_value_current_year], verbose_name=' year'),
        ),
    ]
