# Generated by Django 4.0.2 on 2022-03-07 12:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_year_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
