# Generated by Django 4.0.2 on 2022-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_alter_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='transaction_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
