# Generated by Django 4.0.2 on 2022-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='transaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
